# Dependencies
highlighter:      rouge

# Permalinks
permalink:        /:categories/:slug/
# relative_permalinks: true

# Setup
title:      'Hola, Bienvenidos al' 
description:            "Espacio de Raihan"
tagline:          'Writing on my works and thoughts'
url:              https://raihantarek.github.io
logo:             /github.png
baseurl:          ''

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

author:
  name: 'raihan'
  url: https://github.com/raihantarek
  

# Post-related global variables
defaultpostimage: /public/image.jpg

# For a global message in the head
message: 

exclude: []
